; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp32-c3

[env]
build_src_filter = +<*> -<.git/> -<.svn/> -<example/> -<examples/> -<test/> -<tests/>
lib_deps = 
	olikraus/U8g2@^2.35.30
	https://github.com/dvarrel/AsyncTCP.git
	https://github.com/me-no-dev/ESPAsyncWebServer.git
	thelastoutpostworkshop/GPIOViewer @ ^1.5.6
	asukiaaa/XboxSeriesXControllerESP32_asukiaaa@^1.1.0

[env:esp32-c3]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
upload_port = COM5
monitor_port = COM5
monitor_speed = 115200
build_flags = 
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DARDUINO_USB_MODE=1
